### ISSUE TITLE
Search for trending user

### ISSUE THREAD

**Issue by arojunior** [arojunior/awesome-feed#23]
Search for trending users and update right column

![captura de tela 2017-10-16 as 22 21 04](https://user-images.githubusercontent.com/7604033/31640966-602766ec-b2c0-11e7-8925-6750fbf40f7d.png)

**Comment by thatbraxguy** [comment]
Can I tackle this?

**Comment by arojunior** [comment]
I didn't find how to get this information with Github GraphQL API, but I think this repo could help: [https://github.com/huchenme/github-trending-api](https://github.com/huchenme/github-trending-api)
